"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "./components/nav/Nav";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [searchBar, setSearchBar] = useState(false);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav searchBar={searchBar} setSearchBar={setSearchBar} />
        <div
          className={`mt-10vh transition-transform duration-500 ${
            searchBar
              ? "transform translate-y-0"
              : "transform translate-y-[-10vh]"
          }`}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
